POST http://localhost:8081/apis/customer/signup
Content-Type: application/json

{
  "name": "김철수",
  "email": "test@test.com",
  "phone": "010-1111-2222",
  "password": "1111",
  "address": "경기도 남양주시 다산동 중흥아파트 1002-212"
}